package cn.yq.springmvc.entity;

import java.io.Serializable;
import java.util.Date;

public class Account implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.password_digest
     *
     * @mbg.generated
     */
    private String passwordDigest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.salt
     *
     * @mbg.generated
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.last_signin
     *
     * @mbg.generated
     */
    private Date lastSignin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table accounts
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.id
     *
     * @return the value of accounts.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.id
     *
     * @param id the value for accounts.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.account
     *
     * @return the value of accounts.account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.account
     *
     * @param account the value for accounts.account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.password_digest
     *
     * @return the value of accounts.password_digest
     *
     * @mbg.generated
     */
    public String getPasswordDigest() {
        return passwordDigest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.password_digest
     *
     * @param passwordDigest the value for accounts.password_digest
     *
     * @mbg.generated
     */
    public void setPasswordDigest(String passwordDigest) {
        this.passwordDigest = passwordDigest == null ? null : passwordDigest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.salt
     *
     * @return the value of accounts.salt
     *
     * @mbg.generated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.salt
     *
     * @param salt the value for accounts.salt
     *
     * @mbg.generated
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.last_signin
     *
     * @return the value of accounts.last_signin
     *
     * @mbg.generated
     */
    public Date getLastSignin() {
        return lastSignin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.last_signin
     *
     * @param lastSignin the value for accounts.last_signin
     *
     * @mbg.generated
     */
    public void setLastSignin(Date lastSignin) {
        this.lastSignin = lastSignin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Account other = (Account) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAccount() == null ? other.getAccount() == null : this.getAccount().equals(other.getAccount()))
            && (this.getPasswordDigest() == null ? other.getPasswordDigest() == null : this.getPasswordDigest().equals(other.getPasswordDigest()))
            && (this.getSalt() == null ? other.getSalt() == null : this.getSalt().equals(other.getSalt()))
            && (this.getLastSignin() == null ? other.getLastSignin() == null : this.getLastSignin().equals(other.getLastSignin()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAccount() == null) ? 0 : getAccount().hashCode());
        result = prime * result + ((getPasswordDigest() == null) ? 0 : getPasswordDigest().hashCode());
        result = prime * result + ((getSalt() == null) ? 0 : getSalt().hashCode());
        result = prime * result + ((getLastSignin() == null) ? 0 : getLastSignin().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", account=").append(account);
        sb.append(", passwordDigest=").append(passwordDigest);
        sb.append(", salt=").append(salt);
        sb.append(", lastSignin=").append(lastSignin);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}